language: cpp

compiler:
        - clang
        - gcc

env:
        - BUILD_TYPE=Debug

install:
        - mkdir build
        - cd build
        - cmake ..
        - make

os:
        - linux
        - osx
