language: cpp

compiler:
        - clang
        - gcc

env:
        - BUILD_TYPE=Debug

before_script:
        - mkdir build
        - cd build
        - cmake ..

script: make

os:
        - linux
        - osx
