language: cpp

compiler:
        - clang
        - gcc

env:
        - BUILD_TYPE=Debug

before_install:
        - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
        - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

install:
        - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
        - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
        - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

before_script:
        - cd build
        - cmake ..

script: make

os:
        - linux
        - osx
